jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t aqua-docker-test:${CIRCLE_SHA1} .
      - run:
          name: Login to Aqua Repository
          command: docker login registry.aquasec.com -u ${AQUA_USER} -p ${AQUA_PASSWORD}
      - run:
          name: Install scannercli
          command: |
            wget --user=${AQUA_USER} --password=${AQUA_PASSWORD} https://download.aquasec.com/scanner/5.3.0/scannercli
            mv scannercli /usr/local/bin
      - run:
          name: Scan the local image with scannercli
          command: scannercli scan --host=${AQUA_CONSOLE} --user={AQUA_SCANNER_USER} --password=${AQUA_SCANNER_PASSWORD} --local=aqua-docker-test:${CIRCLE_SHA1}
workflows:
  version: 2
  release:
    jobs:
      - build:
          context:
            - aqua
